### ISSUE TITLE
Problems while creating new Files or Images

### ISSUE THREAD

**Issue by gbastien** [collective/collective.fingerpointing#8]
Hi @hvelarde 

as we have such kind of functionality in our package, we are evaluating this one that is promising ;-) nevertheless :

1. with Plone 4.3.7 while adding :
  - an Image : the HTML tag is printed to the log (`action=object created object=<img src="http://localhost:8081/mc30b/image.2016-02-24.2681509072/image" alt="" title="" height="0" width="0" />`);
  - a File : the binary content of the file is printed to the log;

1. If using portal_factory/Archetypes, "object created" are printed several times to the log :
  - `action=object created object=<img src="http://localhost:8081/mc30b/portal_factory/Image/image.2016-02-24.2681509072/image" alt="" title="" height="0" width="0" />`
  - `action=object created object=<img src="http://localhost:8081/mc30b/image.2016-02-24.2681509072/image" alt="" title="" height="0" width="0" />`

1. it would be nice to have the full path to the created element because we have `"action=object modified object=<ATDocument at my-doc-id>"`

I would like to contribute but I need your opinion about these problems, maybe it behaves correctly with Dexterity?  Do you want also correct support for AT?

Thank you!

Gauthier

**Comment by hvelarde** [comment]
I released this package very early because I wanted to attract more people with the same use case; in fact we don't have any requirement right now but I always though this was a missing feature on Plone.

1. feel free to fix the behavior described
1. it is a problem with Archetypes implementation: remember it creates a temporary object in `portal_factory` before the real object is created; maybe we can hide that one (@pcdummy, thoughs?)
1. I agree; do you know if there is a standard format for audit log files?

please open different branches and PR to address each issue; that way we can review and merge faster.

**Comment by gbastien** [comment]
Hi,

we will propose various fixes as soon as possible.

Thank you for your response,

Gauthier

**Comment by frisi** [comment]
@gbastien about 2):

`zope.lifecycleevent.IObjectCreatedEvent` is fired multiple times for archetypes.
we'd be better off using `Products.Archetypes.interfaces.IObjectInitializedEvent`

about 3):
@hvelarde added #10 and i think we should add the .getPhysicalPath() of an object (if applicable to the logged action)

**Comment by hvelarde** [comment]
I added a new issue for addressing 2.

**Comment by hvelarde** [comment]
@gbastien please feel free to help us solving those issues; I'm closing this as we have now #38 and #39
